### ISSUE TITLE
Generate verbose syntax from regexp

### ISSUE THREAD

**Issue by a-komarev** [SimpleRegex/SRL-PHP#35] opened 2016-09-07 15:19 UTC
It would be great to have inverse behavior.

User provides:

```php
/^([A-Z0-9._%+-])+@[A-Z0-9.-]+\.[A-Z]{2,}$/i
```

Output:

```
begin with any of (digit, letter, one of "._%+-") once or more,
literally "@",
any of (digit, letter, one of ".-") once or more,
literally ".",
letter at least 2,
must end, case insensitive
```

**Comment by KarimGeiger** [comment] 2016-09-07 15:24
Duplicate of #9

**Closed by KarimGeiger** 2016-09-07 15:24 UTC
